# Generated by Django 5.0.2 on 2025-03-03 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_member_address_remove_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewed_on', models.DateTimeField(auto_now_add=True)),
                ('previous_end_date', models.DateField()),
                ('new_end_date', models.DateField()),
                ('renewal_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to='members.member')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.membership')),
            ],
        ),
    ]
