# Generated by Django 5.0.2 on 2025-03-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_membershiphistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
