# Generated by Django 5.0.2 on 2025-03-03 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_membership_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiphistory',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='members.membership'),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='renewed_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
