# Generated by Django 5.0.2 on 2025-03-04 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_membershiphistory_membership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiphistory',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.membership'),
        ),
        migrations.AlterField(
            model_name='membershiphistory',
            name='renewed_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
